# Generated by Django 4.0.5 on 2022-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
